name: Deploy Backend

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy-backend:
        name: Deploy backend
        runs-on: [self-hosted, linux]

        steps:
            - run: cd french-toast-weekly-report-2-api
            - name: Pulling changes
              run: git pull
            - name: Run docker-compose
              run: docker-compose up -d --build
