name: Deploy Backend

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy-backend:
        name: Deploy backend
        runs-on: [self-hosted, linux]

        steps:
            - uses: actions/checkout@v2
            - name: Run docker-compose
              run: docker-compose up -d --build
